version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"        
    env_file:
      - .env             
    volumes:
      - .:/app             
    working_dir: /app
    command: flask run --host=0.0.0.0 --reload
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: always   
